### ISSUE TITLE
Where is the version you demoed on YouTube

### ISSUE THREAD

**Issue by davecader** [danroth27/BestForYouRecipes#11]
Hello Daniel

Do you know where I can find the version of the BestForYouRecipes project that you demonstrated in your Build 2023 Demo Sessions YouTube video. The version that you demoed had more features that this version here.

**Comment by lucasmicheleto** [comment]
> Hello Daniel
> 
> Do you know where I can find the version of the BestForYouRecipes project that you demonstrated in your Build 2023 Demo Sessions YouTube video. The version that you demoed had more features that this version here.

Have you ever check out dotnet8 branch?

**Comment by behroozbc** [comment]
please check this branch https://github.com/danroth27/BestForYouRecipes/tree/dotnet8rtm

**Comment by danroth27** [comment]
The main branch is now updated to be a Blazor Web App based on .NET 8.
