### ISSUE TITLE
Git tag commits for preview releases

### ISSUE THREAD

**Issue by indcoder** [danroth27/BestForYouRecipes#5]
Perhaps till we reach RC releases, for the dotnet8 branch, if you can tag the commit with the preview version, it would help us clone the codebase that matches with the latest dotnet SDK public releases 

<img width="954" alt="image" src="https://github.com/danroth27/BestForYouRecipes/assets/2099300/a410c327-52cb-4002-9479-42dde2db4b56">

As a workaround, had to hunt for the commit before the preview 7 version.

<img width="506" alt="image" src="https://github.com/danroth27/BestForYouRecipes/assets/2099300/c6d8800c-1174-45e5-89e8-8401adea5e7a">

On the other hand, looking forward to the autorender feature in 7 😊

**Comment by danroth27** [comment]
Sorry about that! I will avoid pushing changes to dotnet8 that require an unreleased version going forward.
